# fly.toml app configuration file generated for romupunktbot on 2026-01-19T00:08:04Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "romupunktbot"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"

[processes]
  app = "python bot.py"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
